backend:
  name: git-gateway
  branch: master
 
media_folder: static/img
public_folder: ../../static/img
publish_mode: editorial_workflow
locale: 'de'
logo_url: /CMS-logo.svg

collections:
  - name: "content"
    label: "Inhalte"
    files:
      - label: Startseite
        name: "indexfile"
        file: src/data/index.md
        fields:
          - label: "Startseite"
            name: "index"
            widget: "object"
            fields:
            - label: "Vorstellung"
              name: "intro"
              widget: "object"
              fields:
              - { label: "Überschrift", name: "header", widget: "string" }
              - { label: "Text", name: "text", widget: "markdown" }
            - label: "Banner"
              name: "topbanner"
              widget: "object"
              fields:
              - { label: "Titel", name: "title", widget: "string" }
              - { label: "Untertitel", name: "subtitle", widget: "string" }
              - label: "Bild"
                name: "image" 
                widget: "image"
            - label: "Blog"
              name: "blog"
              widget: "object"
              fields:
              - label: "Blogposts"
                name: "blogposts"
                widget: "list"
                fields:
                  - { label: "Titel", name: "title", widget: "string" }
                  - { label: "Text", name: "text", widget: "markdown"}
                  - {label: "Date", name: "date" , widget: "datetime", default: "", date_format: "DD.MM.YYYY", time_format: "", format: "L", picker_utc: true}
                  - { label: "Ersteller", name: "creator", widget: "select", options: ["Max Mustermann", "Bernd Beispiel", "Volker Vorlage"] }
                  - { label: "Bild", name: "image", widget: "image", required: false}
            - label: "ImageShowcase"
              name: "imageshowcase"
              widget: "object"
              fields:
              - label: "Bild"
                name: "image"
                widget: "image"
